- src/hpa/Point.hx
- src/hpa/Transform.hx
- test/Test.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/haxe-phaser-ash/4)
> Added abstract Point

- src/hpa/Point.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/5)
> Allow Point to be used in unit test

- src/whiplash/Lib.hx
- src/whiplash/Point.hx
- src/whiplash/Sprite.hx
- src/whiplash/SpriteSystem.hx
- src/whiplash/Transform.hx
- test/Test.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/6)
> Renamed hpa to whiplash everywhere

- src/whiplash/Point.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/7)
> Point methods

- src/whiplash/Point.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/8)
> Added commutative on operators

- src/whiplash/Lib.hx
- src/whiplash/Text.hx
- src/whiplash/TextSystem.hx
- test/Test.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/9)
> Added text support

- src/whiplash/Point.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/11)
> Point getLength

- src/whiplash/math/Angle.hx
Helper to treat angles
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/12)
> Angle helper

- src/whiplash/Point.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/14)
> Add missing function for test

- src/whiplash/Lib.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/13)
> Updated Lib

- src/whiplash/Lib.hx
- src/whiplash/TileSprite.hx
- src/whiplash/TileSpriteSystem.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/16)
> TileSprites

- .gitmodules
- .travis.yml
- README.md
- test.hxml
- test/build.hxml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/17)
> Travis setup

- src/whiplash/Lib.hx
- src/whiplash/TilemapLayer.hx
- src/whiplash/TilemapLayerSystem.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/18)
> TilemapLayer

- src/whiplash/Lib.hx
- src/whiplash/ParticleSystem.hx
- src/whiplash/ParticleSystemSystem.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/19)
> Added particle system system

- .gitmodules
- Makefile
- src/whiplash/Lib.hx
- src/whiplash/babylon/DirectionalLight.hx
- src/whiplash/babylon/DirectionalLightSystem.hx
- src/whiplash/babylon/FreeCamera.hx
- src/whiplash/babylon/FreeCameraSystem.hx
- src/whiplash/babylon/Mesh.hx
- src/whiplash/babylon/MeshSystem.hx
- src/whiplash/babylon/ParticleSystem.hx
- src/whiplash/babylon/ParticleSystemSystem.hx
- src/whiplash/babylon/PointLight.hx
- src/whiplash/babylon/PointLightSystem.hx
- src/whiplash/babylon/Transform3d.hx
- src/whiplash/phaser/Graphics.hx
- src/whiplash/phaser/GraphicsSystem.hx
- src/whiplash/phaser/Point.hx
- src/whiplash/phaser/Sprite.hx
- src/whiplash/phaser/SpriteSystem.hx
- src/whiplash/phaser/Text.hx
- src/whiplash/phaser/TextSystem.hx
- src/whiplash/phaser/TileSprite.hx
- src/whiplash/phaser/TileSpriteSystem.hx
- src/whiplash/phaser/TilemapLayer.hx
- src/whiplash/phaser/TilemapLayerSystem.hx
- src/whiplash/phaser/Transform.hx
- test.hxml
- test/Makefile
- test/Test.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/20)
> Added an option to enable backends

- src/whiplash/Lib.hx
- src/whiplash/babylon/Sprite3d.hx
- src/whiplash/babylon/Sprite3dSystem.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/21)
> Sprite3d support

- src/whiplash/Lib.hx
- src/whiplash/babylon/components/Camera.hx
- src/whiplash/babylon/components/Light.hx
- src/whiplash/babylon/components/Mesh.hx
- src/whiplash/babylon/components/ParticleSystem.hx
- src/whiplash/babylon/components/SceneObject.hx
- src/whiplash/babylon/components/Sprite3d.hx
- src/whiplash/babylon/components/Transform3d.hx
- src/whiplash/babylon/systems/CameraSystem.hx
- src/whiplash/babylon/systems/LightSystem.hx
- src/whiplash/babylon/systems/MeshSystem.hx
- src/whiplash/babylon/systems/ParticleSystemSystem.hx
- src/whiplash/babylon/systems/Sprite3dSystem.hx
- test/Test.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/23)
> Code organized in packages for babylon

- .gitignore
- src/whiplash/Input.hx
- src/whiplash/Lib.hx
- src/whiplash/math/Point.hx
- src/whiplash/phaser/Transform.hx
- test/Test.hx
- test/index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/24)
> Added Input static class

- src/whiplash/Lib.hx
- src/whiplash/babylon/components/Material.hx
- src/whiplash/babylon/systems/MaterialSystem.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/25)
> Material system, support of time

- src/whiplash/babylon/systems/CameraSystem.hx
- src/whiplash/common/components/Active.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/26)
> Camera active concept

- src/whiplash/babylon/components/Camera.hx
- src/whiplash/babylon/systems/CameraSystem.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/27)
> Camera rotation was not using a quaternion

- src/whiplash/Input.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/28)
> Updated Input

- src/whiplash/Lib.hx
- src/whiplash/babylon/systems/VisibilitySystem.hx
- src/whiplash/common/components/Visible.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/30)
> Add visibility system

- src/whiplash/math/Vector2.hx
- src/whiplash/math/Vector3.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/31)
> Added forwardStatics

- src/whiplash/Lib.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/33)
> Set a class on babylon canvas

- src/whiplash/Input.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/35)
> Gamepad support

- src/whiplash/Input.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/36)
> postUpdate and update

- src/whiplash/Input.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/37)
> Added button names

- src/whiplash/Input.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/38)
> Added getZWAxes

- src/whiplash/Input.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/39)
> Fixed mouse coordinates

- src/whiplash/Input.hx
- src/whiplash/Lib.hx
- src/whiplash/math/Vector2.hx
- test.hxml
- test/Test.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/40)
> Removed runtime options and use of compile options

- src/whiplash/Lib.hx
- src/whiplash/phaser/BitmapText.hx
- src/whiplash/phaser/BitmapTextSystem.hx
- src/whiplash/phaser/Sprite.hx
- src/whiplash/phaser/SpriteSystem.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/41)
> Added physics and BitmapText

- src/whiplash/Lib.hx
- src/whiplash/phaser/Group.hx
- src/whiplash/phaser/GroupSystem.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/42)
> Added phaser Group support

- src/whiplash/Input.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/43)
> Fix touchEnd on mobile chrome

- src/whiplash/Lib.hx
- src/whiplash/phaser/Emitter.hx
- src/whiplash/phaser/EmitterSystem.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/44)
> Added phaser Emitter support

- src/whiplash/Application.hx
- src/whiplash/Lib.hx
- src/whiplash/babylon/components/Material.hx
- src/whiplash/babylon/systems/MaterialSystem.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/46)
> Cleaning code, optional phaser, Input integration

- src/whiplash/phaser/TileSprite.hx
- src/whiplash/phaser/TileSpriteSystem.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/49)
> Fixed TileSprite

- src/whiplash/DataManager.hx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/firefalcom/whiplash/50)
> Updated DataManager for normal maps
